### ISSUE TITLE
Graves not spawning (spigot 1.21)

### ISSUE THREAD

**Issue by atraira** [AvarionMC/graves#65]
### Checks

- [X] I have checked that this issue has not already been reported (even among closed issues).
- [X] I have confirmed this bug exists on the [latest version](https://www.spigotmc.org/resources/graves.116202/history).
- [ ] I just click random checkboxes without actually reading them.

### Version

4.9.4

### Server version

1.21

### Plugin list

[16:33:49] [Server thread/INFO]: Plugins (15): LuckPerms, EternalLight, Minepacks, RHLeafDecay, Links, MinecartSpeedPlus, Vault, ChestSort, dynmap, Essentials, EssentialsChat, Graves, EssentialsSpawn, GriefPrevention, DiscordSRV

### Expected behavior

graves spawn

### Actual behavior

graves don't spawn; items are dropped on ground like vanilla minecraft. plugin commands do function.

### Stacktrace if applicable (no screenshots!)

>graves reload
[16:31:41] [Server thread/WARN]: Unexpected exception while parsing console command "graves reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'graves' in plugin Graves v4.9.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchCommand(CraftServer.java:921) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchServerCommand(CraftServer.java:906) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.dedicated.DedicatedServer.br(DedicatedServer.java:431) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:407) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "priorityStr" is null
        at org.avarion.graves.Graves.getEventPriority(Graves.java:245) ~[?:?]
        at org.avarion.graves.Graves.registerListeners(Graves.java:211) ~[?:?]
        at org.avarion.graves.Graves.reload(Graves.java:170) ~[?:?]
        at org.avarion.graves.command.GravesCommand.onCommand(GravesCommand.java:206) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 9 more

### Additional information

recently updated my spigot server to 1.21 and this plugin is one of the ones ive had issues with, ty for any help!

**Comment by svaningelgem** [comment]
Thanks for the report @atraira . Is it possible to share your config.yml?

**Comment by atraira** [comment]
sure thing!
```
config-version: 3 # Config version, you should never manually change this.

###############
# Core Config #
###############
# Core config for backend processes or misc options.
# If you are looking to edit graves the main grave config file is grave.yml.
settings:
  ###########
  # Storage #
  ###########
  # Data storage system.
  storage:
    type: SQLITE # SQLITE, More storage types will be added in the future.
    sqlite: # Unless you know what you're doing leave options under sqlite default.
      journal-mode: "WAL" # https://www.sqlite.org/pragma.html#pragma_journal_mode
      synchronous: "OFF" # https://www.sqlite.org/pragma.html#pragma_synchronous

  #########
  # Cache #
  #########
  # Data storage system.
  cache:
    type: NORMAL # Cache type.

  #########
  # Debug #
  #########
  # Debug information, debug level 2 can be useful in finding out why a Grave does not spawn on your server.
  debug:
    admin: # UUID or name of admins to send debug information to. https://mcuuid.net/
      - "c59ac6d2-4851-4183-a9f7-15d1a293eed6" # Ranull
      - "069a79f4-44e9-4726-a5be-fca90e38aaf5" # Notch
    level: 0 # 0 = Nothing, 1 = Information, 2 = Failures

  #########
  # Dump #
  #########
  # Dump server information to help debug the plugin.
  # Methods: HASTEBIN, FILE
  dump:
    method: HASTEBIN # HASTEBIN, FILE

  ##########
  # Update #
  ##########
  update:
    check: true # Should Graves try and check for an update.

  #################
  # Compatibility #
  #################
  compatibility:
    warning: true # Warn when a plugin to have known incompatibilities is detected.

  ###############
  # Integration #
  ###############
  # Enable/Disable integrations into other plugins, if you are having errors relating to another plugin
  # try disabling them here.
  integration:
    multipaper: # https://multipaper.io/
      enabled: true # Should MultiPaper integration be enabled.
    multicache: # https://github.com/PestoNotPasta/MultiCache/
      enabled: true # Should MultiCache integration be enabled.
    vault: # https://www.spigotmc.org/resources/vault.34315/
      enabled: true # Should Vault integration be enabled.
    protocollib: # https://www.spigotmc.org/resources/protocollib.1997/
      enabled: true # Should ProtocolLib integration be enabled.
    worldedit: # https://dev.bukkit.org/projects/worldedit/
      enabled: true # Should WorldEdit integration be enabled.
      write: true # Should Graves write its schematics into its own folder.
    worldguard: # https://dev.bukkit.org/projects/worldguard/
      enabled: true # Should WorldGuard integration be enabled.
    towny: # https://www.spigotmc.org/resources/towny-advanced.72694/
      enabled: true # Should Towny integration be enabled.
    griefdefender: # https://www.spigotmc.org/resources/griefdefender.68900/
      enabled: true # Should GriefDefender integration be enabled.
    furniturelib: # https://www.spigotmc.org/resources/furniturelibary.9368/
      enabled: true # Should FurnitureLib integration be enabled.
    furnitureengine: # https://www.spigotmc.org/resources/furnitureengine.97134/
      enabled: true # Should FurnitureEngine integration be enabled.
    protectionlib: # https://www.spigotmc.org/resources/protectionlib.9368/
      enabled: true # Should ProtectionLib integration be enabled.
    itemsadder: # https://www.spigotmc.org/resources/itemsadder.73355/
      enabled: true # Should ItemsAdder integration be enabled.
      write: true # Should Graves write its data into the ItemsAdder data folder.
    oraxen: # https://www.spigotmc.org/resources/oraxen.72448/
      enabled: true # Should Oraxen integration be enabled.
      write: true # Should Graves write its pack into the Oraxen pack folder.
    placeholderapi: # https://www.spigotmc.org/resources/placeholderapi.6245/
      enabled: true # Should PlaceholderAPI integration be enabled.
    skript: # https://github.com/SkriptLang/Skript/
      enabled: true # Should Skript integration be enabled.
    chestsort: # https://www.spigotmc.org/resources/chestsort.59773/
      enabled: true # Should ChestSort integration be enabled.
    minimessage: # https://docs.adventure.kyori.net/minimessage/index.html
      enabled: true # Should MiniMessage integration be enabled.
    minedown: # https://github.com/Phoenix616/MineDownPlugin/
      enabled: true # Should MineDown integration be enabled.
    playernpc: # https://www.spigotmc.org/resources/playernpc.93625/
      enabled: true # Should PlayerNPC integration be enabled.
    itembridge: # https://www.spigotmc.org/resources/itembridge.77080/
      enabled: true # Should ItemBridge integration be enabled.
```

**Comment by svaningelgem** [comment]
Hi  @atraira , I just released 4.9.5, and I think that would solve your issue.

Can you verify by updating?

Thanks!

**Comment by atraira** [comment]
hmm, unfortunately this has actually made the problem worse lol

graves still do not spawn, but they attempt to spawn and now consume everything in the inventory and drop a graves compass 

graves commands also no longer work

>[21:48:58] [Server thread/ERROR]: Error occurred while enabling Graves v4.9.5 (Is it up to date?)
java.lang.IllegalArgumentException: Recipe must have non-AIR result.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.CraftingRecipe.<init>(CraftingRecipe.java:21) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.inventory.CraftComplexRecipe.<init>(CraftComplexRecipe.java:17) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.world.item.crafting.IRecipeComplex.toBukkitRecipe(IRecipeComplex.java:43) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.world.item.crafting.RecipeHolder.toBukkitRecipe(RecipeHolder.java:16) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:24) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:10) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.avarion.graves.manager.RecipeManager.unload(RecipeManager.java:56) ~[?:?]
        at org.avarion.graves.manager.RecipeManager.reload(RecipeManager.java:35) ~[?:?]
        at org.avarion.graves.manager.RecipeManager.<init>(RecipeManager.java:31) ~[?:?]
        at org.avarion.graves.Graves.registerRecipes(Graves.java:258) ~[?:?]
        at org.avarion.graves.Graves.onEnable(Graves.java:88) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]




>gamemode survival atraira
[21:50:11] [Server thread/INFO]: CONSOLE issued server command: /gamemode survival atraira
[21:50:11] [Server thread/INFO]: Set game mode survival for ~Invis.
[21:50:14] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Graves v4.9.5
java.lang.NullPointerException: Cannot invoke "org.avarion.graves.compatibility.Compatibility.setBlockData(org.bukkit.Location, org.bukkit.Material, org.avarion.graves.type.Grave, org.avarion.graves.Graves)" because the return value of "org.avarion.graves.Graves.getCompatibility()" is null
        at org.avarion.graves.manager.BlockManager.createBlock(BlockManager.java:67) ~[?:?]
        at org.avarion.graves.manager.GraveManager.placeGrave(GraveManager.java:291) ~[?:?]
        at org.avarion.graves.listener.EntityDeathListener.execute(EntityDeathListener.java:490) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:938) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:914) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1528) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:971) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1069) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1989) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1674) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.world.level.block.Block.a(Block.java:398) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.world.entity.Entity.a(Entity.java:1495) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:408) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1477) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1308) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(SourceFile:142) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:50) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandler.bB(SourceFile:121) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1213) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
[21:50:14] [Server thread/INFO]: Atraira fell from a high place
[21:52:59] [Server thread/INFO]: Atraira issued server command: /grave
[21:52:59] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'grave' in plugin Graves v4.9.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchCommand(CraftServer.java:921) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:414) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1842) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$7(PlayerConnection.java:1818) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.avarion.graves.compatibility.Compatibility.getSkullItemStack(org.avarion.graves.type.Grave, org.avarion.graves.Graves)" because the return value of "org.avarion.graves.Graves.getCompatibility()" is null
        at org.avarion.graves.manager.ItemStackManager.createGraveListItemStack(ItemStackManager.java:113) ~[?:?]
        at org.avarion.graves.manager.GUIManager.setGraveListItems(GUIManager.java:96) ~[?:?]
        at org.avarion.graves.manager.GUIManager.openGraveList(GUIManager.java:72) ~[?:?]
        at org.avarion.graves.manager.GUIManager.openGraveList(GUIManager.java:27) ~[?:?]
        at org.avarion.graves.command.GravesCommand.onCommand(GravesCommand.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 28 more
        
        

>[21:53:02] [Server thread/INFO]: Atraira issued server command: /graves
[21:53:02] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'graves' in plugin Graves v4.9.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchCommand(CraftServer.java:921) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:414) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1842) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$7(PlayerConnection.java:1818) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.avarion.graves.compatibility.Compatibility.getSkullItemStack(org.avarion.graves.type.Grave, org.avarion.graves.Graves)" because the return value of "org.avarion.graves.Graves.getCompatibility()" is null
        at org.avarion.graves.manager.ItemStackManager.createGraveListItemStack(ItemStackManager.java:113) ~[?:?]
        at org.avarion.graves.manager.GUIManager.setGraveListItems(GUIManager.java:96) ~[?:?]
        at org.avarion.graves.manager.GUIManager.openGraveList(GUIManager.java:72) ~[?:?]
        at org.avarion.graves.manager.GUIManager.openGraveList(GUIManager.java:27) ~[?:?]
        at org.avarion.graves.command.GravesCommand.onCommand(GravesCommand.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 28 more

**Comment by svaningelgem** [comment]
Hmmm, this looks to be something not graves related:
```
java.lang.IllegalArgumentException: Recipe must have non-AIR result.
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
at org.bukkit.inventory.CraftingRecipe.(CraftingRecipe.java:21) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_21_R1.inventory.CraftComplexRecipe.(CraftComplexRecipe.java:17) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
at net.minecraft.world.item.crafting.IRecipeComplex.toBukkitRecipe(IRecipeComplex.java:43) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
at net.minecraft.world.item.crafting.RecipeHolder.toBukkitRecipe(RecipeHolder.java:16) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
at org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:24) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
at org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:10) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
at org.avarion.graves.manager.RecipeManager.unload(RecipeManager.java:56) ~[?:?]
```

What graves is doing in this part of the code is looking to unregister the token recipe. The problem is that some of the recipes are invalid it seems. And when iterating through them, spigot is crashing. Nothing to do with graves in that sense.

On my side this starts up normally, and behaves normally:
![image](https://github.com/user-attachments/assets/a6c94542-45a5-4331-ac8f-e4a0f8d5d7f5)

(fyi, you could just type `/kill` for testing, no need to jump from high)

Ofcourse, I didn't have your list of plugins activated, but I'm guessing one of the others have an invalid "AIR" target registered.
I'll add some checks in there to ensure this is captured, but it shouldn't be captured honestly. It should be fixed in the other plugin...

**Comment by svaningelgem** [comment]
Although I think it'll be an endless loop if I capture this exception because the iterator might not advance and be stuck on the faulty recipe.

**Comment by atraira** [comment]
sounds good! ill get in touch this weekend

**Comment by svaningelgem** [comment]
Closing due to inactivity.
